//
// Created by Sebastian on 05/12/2017.
//

#ifndef ASSIGNMENT4_MATERIALTYPES_H
#define ASSIGNMENT4_MATERIALTYPES_H

enum MaterialType{
    PHONG,
    TRANSMITTANCE,
    REFLECTION,
    LIGHT,
    PBR
};

#endif //ASSIGNMENT4_MATERIALTYPES_H
