//
// Created by Sebastian on 05/12/2017.
//

#ifndef ASSIGNMENT4_MATERIALTYPES_H
#define ASSIGNMENT4_MATERIALTYPES_H

enum MaterialType{
    DIFFUSE_AND_GLOSSY,
    REFLECTION_AND_REFRACTION,
    REFLECTION
};

#endif //ASSIGNMENT4_MATERIALTYPES_H
